language: generic
sudo: required
services:
  -docker

before_install:
  - docker build -t zuhaalfaraj/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true zuhaalfaraj/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-132595846917"
  bucket_path: "docker-react"
  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY